/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatapp;

import java.awt.*;
import java.io.IOException;
import java.net.Socket;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jimd
 */
public class Registor extends javax.swing.JFrame {
    public Connection connection;
    public PreparedStatement stmt;
    public ResultSet resultSet;
    public static final String jdbc = "jdbc:mysql://localhost:3306/chatapp";
    public static final String username = "root";
    public static final String pass = "";

    /**
     * Creates new form Register
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        fnameLabel = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        RegistrationLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        pwdError = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        nameErr = new javax.swing.JLabel();
        emailErr = new javax.swing.JLabel();
        confErr = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setName("RegistrationPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(315, 287));

        formContainer.setName("registrationCon"); // NOI18N
        formContainer.setPreferredSize(new java.awt.Dimension(315, 287));
        fnameLabel.setText("Name:");

        fname.setColumns(30);
        fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        fname.setMargin(new java.awt.Insets(10, 3, 3, 6));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        emailLabel.setText("Email :");

        pwdLabel.setText("password:");

        registerBtn.setBackground(new java.awt.Color(0, 255, 255));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        RegistrationLabel.setText("Registration");

        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        emailField.setMargin(new java.awt.Insets(10, 3, 3, 6));
        emailField.setPreferredSize(new java.awt.Dimension(64, 30));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        PasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PasswordField.setMargin(new java.awt.Insets(10, 3, 3, 6));
        PasswordField.setName(""); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        confirmPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        confirmPassField.setMargin(new java.awt.Insets(10, 3, 3, 6));
        confirmPassField.setPreferredSize(new java.awt.Dimension(90, 30));
        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setActionCommand("");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        confirmLabel.setText("confirm:");

        nameErr.setName(""); // NOI18N

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(fnameLabel)
                        .addGap(24, 24, 24)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                                .addComponent(confirmLabel)
                                .addGap(18, 18, 18)
                                .addComponent(confirmPassField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pwdError, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pwdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(emailErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
            .addGroup(formContainerLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formContainerLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(confErr, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formContainerLayout.setVerticalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(emailErr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmLabel))
                .addGap(8, 8, 8)
                .addComponent(confErr, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(registerBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome");
        welcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        welcome.setName("welcome"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        welcome.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == loginBtn){
            Login login = new Login("Login");
            this.dispose();
//            this.setSize(330,246);
//            this.mainPanel.setVisible(false);
//            login.loginMainPanel.setVisible(true);
//            login.loginMainPanel.setSize(330,287);
            login.setVisible(true);
            login.setSize(400,300);
            login.setVisible(true);
            login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if(evt.getSource() == registerBtn){
            String Fname = fname.getText();
            String email = emailField.getText();
            String password = String.valueOf(PasswordField.getPassword());
            String confPwd = String.valueOf(confirmPassField.getPassword());
            Boolean err  = false;

            if(Fname.isEmpty()){
                nameErr.setText("First name can't be empty");
                nameErr.setForeground(Color.red);
                err = true;
            }else{
                nameErr.setText("");
            }
                     //   nameErr.setText(Fname);

            if(email.isEmpty()){
                emailErr.setText("Email can't be empty");
                emailErr.setForeground(Color.red);
                err = true;
            }else{
                emailErr.setText("");
            }
          //  emailErr.setText(email);
            if(password.isEmpty()){
                pwdError.setText("Please insert password");
                pwdError.setForeground(Color.red);
                err = true;
            }else{
                pwdError.setText("");
            }

            if(password.length() < 8){
                pwdError.setText("Make your password minlength of 8 chars");
                pwdError.setForeground(Color.red);
                err = true;
            }else{
                pwdError.setText("");
            }
            if(password.isEmpty() || !password.equals(confPwd)){
                confErr.setText("Please confirm your password");
                confErr.setForeground(Color.red);
                err = true;
            }else{
                confErr.setText("");
            }
            if(!err){
                formContainer.setVisible(false);
                this.dispose();
                Socket socket = null;
                try{
                    saveToDatabase(Fname,email,password);

                    socket = new Socket("localhost",8002);
                    ChatAppUI chatAppUI = new ChatAppUI(socket,email);
                    this.setSize(400,400);
                    chatAppUI.setSize(400,400);
                    chatAppUI.setVisible(true);
                    chatAppUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    chatAppUI.readMessage();
                }catch (IOException e){
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fnameActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RegistrationLabel;
    private javax.swing.JLabel confErr;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel emailErr;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JPanel formContainer;
    private javax.swing.JButton loginBtn;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameErr;
    private javax.swing.JLabel pwdError;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

 public Registor(String title) {
//       this.welcome.setVisible(false); 
//       this.fname.setMargin(new Insets(5,5,5,5));
//        this.emailField.setMargin(new Insets(5,5,5,5));
     super(title);
        initComponents();
        this.welcome.setVisible(false);
    }
 
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              Registor registor =  new Registor("Register");
              registor.setSize(350,320);
              registor.setVisible(true);
            }
        });
    }

    private boolean saveToDatabase(String Fname, String email, String password){
        try{
            connection = DriverManager.getConnection(jdbc,username,pass);
            String sql = "INSERT INTO user(name,email,password) VALUES(?,?,?)";
            stmt = connection.prepareStatement(sql);
            stmt.setString(1,Fname);
            stmt.setString(2,email);
            stmt.setString(3,password);
            stmt.executeUpdate(); 
            return true;
        }catch(SQLException e){
            e.printStackTrace();
        }
        return false;
    }

}


